apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: nginx
      labels:
        name: nginx
        tier: front-end
        env: production
    spec:
      containers:
        - name: nginx-controller
          image: ngnix
  replicas: 3
