apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: nginx
      labels:
        name: nginx
        tier: front-end
        env: production
    spec:
      containers:
        - name: nginx-controller
          image: ngnix
  replicas: 3
  selector:
    matchLabels:
      type: front-end
