apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 80    # Port of the Pod 
      port: 80          # Port of the Service
  selector:             # Copied from Pod yaml file labels
      name: nginx       
      tier: front-end
      env: production   